role = "judge_neck"

[pan]
min = 500
max = 2500
center = 1583
invert = false
limit_min_deg = -60.0
limit_max_deg = 60.0

[tilt]
min = 1500
max = 1967
center = 1500
invert = false
limit_min_deg = 0.0
limit_max_deg = 30.0
